### ISSUE TITLE
django-tabbed-changeform-admin v0.1.3 vs django-static-jquery3 v5.0.0

### ISSUE THREAD

**Issue by jayvdb** [zencore-cn/zencore-issues#7]
`django-tabbed-changeform-admin` v0.1.3 refers to `jquery3/jquery.js`

django-static-jquery3 v5.0.0 moved `jquery3/jquery.js` to `jquery/jquery.js` , breaking `django-tabbed-changeform-admin`

**Comment by zencore-cn** [comment]
django-tabbed-changeform-admin upgraded to 0.1.6.

**Comment by jayvdb** [comment]
Thanks
